### ISSUE TITLE
أسبوع و ليس إسبوع 

### ISSUE THREAD

**Issue by MurtadhaS** [bluemix/ArabicTimeAgo#1]
أسبوع و ليس إسبوع

**Comment by bluemix** [comment]
صحيح :)
http://www.almaany.com/ar/dict/ar-en/اسبوع/
شكراً جزيلاً عزيزي ، سيتم التحديث بأقرب وقت 👍

**Comment by bluemix** [comment]
تم التحديث ، شكراً جزيلاً 👍
